In [2]:
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [4]:
b=[1,2,3,4,5,6,7,8,9,9]
print(b,type(b))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 9] <class 'list'>

In [5]:
data=pd.Series(b)
data

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9    9
dtype: int64

In [6]:
data[8]

np.int64(9)

In [7]:
data[1:5]

1    2
2    3
3    4
4    5
dtype: int64

In [6]:
import pandas as pd
data ={
    "Name":['Ali','Ahmad','ALishba','Naila','Nia','Sama'],
    'Age' :[18,22,19,23,25,27],
    'city':['isb','lhr','ldr','Mtl','lhr','Isb'],
    'Score':[14,15,16,17,9,20],
    'subject':['eng','urdu','eng','math','math','phy']
}
df=pd.DataFrame(data)
df

      Name  Age city  Score subject
0      Ali   18  isb     14     eng
1    Ahmad   22  lhr     15    urdu
2  ALishba   19  ldr     16     eng
3    Naila   23  Mtl     17    math
4      Nia   25  lhr      9    math
5     Sama   27  Isb     20     phy

In [7]:
df.shape

(6, 5)

In [8]:
df.size

30

In [9]:
df.mean

<bound method DataFrame.mean of       Name  Age city  Score subject
0      Ali   18  isb     14     eng
1    Ahmad   22  lhr     15    urdu
2  ALishba   19  ldr     16     eng
3    Naila   23  Mtl     17    math
4      Nia   25  lhr      9    math
5     Sama   27  Isb     20     phy>

In [10]:
df

      Name  Age city  Score subject
0      Ali   18  isb     14     eng
1    Ahmad   22  lhr     15    urdu
2  ALishba   19  ldr     16     eng
3    Naila   23  Mtl     17    math
4      Nia   25  lhr      9    math
5     Sama   27  Isb     20     phy

In [11]:
df.head()

      Name  Age city  Score subject
0      Ali   18  isb     14     eng
1    Ahmad   22  lhr     15    urdu
2  ALishba   19  ldr     16     eng
3    Naila   23  Mtl     17    math
4      Nia   25  lhr      9    math

In [12]:
df.head(10)

      Name  Age city  Score subject
0      Ali   18  isb     14     eng
1    Ahmad   22  lhr     15    urdu
2  ALishba   19  ldr     16     eng
3    Naila   23  Mtl     17    math
4      Nia   25  lhr      9    math
5     Sama   27  Isb     20     phy

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      str
 1   Age      6 non-null      int64
 2   city     6 non-null      str
 3   Score    6 non-null      int64
 4   subject  6 non-null      str
dtypes: int64(2), str(3)
memory usage: 372.0 bytes

In [14]:
df.describe()

             Age      Score
count   6.000000   6.000000
mean   22.333333  15.166667
std     3.444803   3.656045
min    18.000000   9.000000
25%    19.750000  14.250000
50%    22.500000  15.500000
75%    24.500000  16.750000
max    27.000000  20.000000

In [18]:

df[['Name', 'Age']]

      Name  Age
0      Ali   18
1    Ahmad   22
2  ALishba   19
3    Naila   23
4      Nia   25
5     Sama   27

In [19]:
df[['Name','city']]

      Name city
0      Ali  isb
1    Ahmad  lhr
2  ALishba  ldr
3    Naila  Mtl
4      Nia  lhr
5     Sama  Isb

In [20]:
df.loc[0]

Name       Ali
Age         18
city       isb
Score       14
subject    eng
Name: 0, dtype: object

In [21]:
df.loc[4]

Name        Nia
Age          25
city        lhr
Score         9
subject    math
Name: 4, dtype: object